In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

### iris 데이터

In [2]:
# 데이터 불러오기
iris = load_iris()

In [3]:
# 데이터 정보
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
# 데이터 프레임 생성
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['specis'] = iris.target
iris_df['specis'] = iris_df['specis'].apply(lambda x: iris.target_names[x])
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        specis  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [5]:
# 입출력 데이터 구성
x_data = iris_df.drop('specis', axis=1)
y_data = iris_df['specis']

x_data.shape, y_data.shape

((150, 4), (150,))

In [6]:
# 타겟 데이터 라벨 인코딩
e = LabelEncoder()
y = e.fit_transform(y_data)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
# 타겟 데이터 원-핫인코딩
y_encoded = to_categorical(y)
y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [8]:
# seed값 설정
np.random.seed(0)
tf.random.set_seed(0)

In [9]:
# 모델 설정
model = Sequential()
# feature 4개
model.add(Dense(16, input_dim=4, activation='relu'))
# target 3종류
# 다중분류 -> softmax
model.add(Dense(3, activation='softmax'))

In [10]:
# 모델 컴파일
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [11]:
# 모델 실행
model.fit(x_data, y_encoded, epochs=50, batch_size=1)

Epoch 1/50
150/150 [==============================] - 1s 1ms/step - loss: 2.4696 - accuracy: 0.3587
Epoch 2/50
150/150 [==============================] - 0s 1ms/step - loss: 0.6565 - accuracy: 0.7039
Epoch 3/50
150/150 [==============================] - 0s 1ms/step - loss: 0.5851 - accuracy: 0.7668
Epoch 4/50
150/150 [==============================] - 0s 1ms/step - loss: 0.5163 - accuracy: 0.8565
Epoch 5/50
150/150 [==============================] - 0s 1ms/step - loss: 0.4615 - accuracy: 0.7828
Epoch 6/50
150/150 [==============================] - 0s 2ms/step - loss: 0.4450 - accuracy: 0.9243
Epoch 7/50
150/150 [==============================] - 0s 1ms/step - loss: 0.3678 - accuracy: 0.9238
Epoch 8/50
150/150 [==============================] - 0s 2ms/step - loss: 0.3627 - accuracy: 0.8599
Epoch 9/50
150/150 [==============================] - 0s 2ms/step - loss: 0.3598 - accuracy: 0.8614
Epoch 10/50
150/150 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.9815

In [12]:
# 정확도
model.evaluate(x_data, y_encoded)

5/5 [==============================] - 0s 2ms/step - loss: 0.0869 - accuracy: 0.9800


[0.08690375834703445, 0.9800000190734863]

In [13]:
# 예측
y_pred = np.argmax(model.predict(x_data), axis=1)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
print(classification_report(y, y_pred ))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.98      0.96      0.97        50
           2       0.96      0.98      0.97        50

    accuracy                           0.98       150
   macro avg       0.98      0.98      0.98       150
weighted avg       0.98      0.98      0.98       150

